### ISSUE TITLE
Is NoTouchID.kext really necessary?

### ISSUE THREAD

**Issue by ffosilva** [TranNgocKhoa/Dell-Latitude-7480-Hackintosh#3]
Since you are using MacBookPro14,1 SMBIOS that doesn't have TouchID, I think you could get a rid of this Kext. I removed here and didn't get extra lag issue, as mentioned here: https://1revenger1.gitbook.io/laptop-guide/prepare-install-macos/disabling-touchid

**Comment by TranNgocKhoa** [comment]
After remove NoTouchID, my machine still work well.
I removed the kext

**Comment by ffosilva** [comment]
Very good!
